### ISSUE TITLE
go test ./... does not work anymore.

### ISSUE THREAD

**Issue by Akavall** [Akavall/GoGamesProject#15]
For some reason, this does not work anymore:

```
kirill@lenovo:~/GoStuff/src/github.com/Akavall/GoGamesProject$ go test ./...
# github.com/Akavall/GoGamesProject
./play_zombie_dice.go:8: main redeclared in this block
	previous declaration at ./basic_server.go:78
```

Though, I could've sworn it worked before, and I don't think anything has changed, just added the README file, so it is confusing...

Not really an issue of course, more like a message...

**Comment by a-temlyakov** [comment]
Hm, that's weird. It still works for me.

**Comment by Akavall** [comment]
It works on my other computer. It works on where I have go version 1.2.1. I upgraded the other one to version 1.4 recently, so I guess that's it, but it is strange...

**Comment by a-temlyakov** [comment]
Yeah, I am on go1.2.1 and it works, so 1.3 or 1.4 must have changed how running unit tests works.

**Comment by a-temlyakov** [comment]
Ok it should be fixed now! Works on my machine with go1.4.2

Though, long term, I think we should eventually remove the multiple main functions

**Comment by Akavall** [comment]
Yeah, I works. Thanks.
