### ISSUE TITLE
I think we need to coordinate on who is going to work on what

### ISSUE THREAD

**Issue by Akavall** [Akavall/GoGamesProject#25]
I think you did a really big step in setting up zombie dice. And I think the next steps a pretty obvious: to build on what you have, e.g, getting rid of the bugs. So it is really easy for us to work on the same thing, which could be redundant! So maybe it is better to coordinate on who is going to do what via github issues?

**Comment by a-temlyakov** [comment]
Yeah, I think we can just use issues... I am going to start creating them here and we can track work through them (like the unit test one).
