### ISSUE TITLE
Continue game shows up as true in brwoser, even though is false in json_string

### ISSUE THREAD

**Issue by Akavall** [Akavall/GoGamesProject#35]
I was trying to make the user facing interface more user friendly, and got completely stuck on this part:

This is in my_branch `kirill_modify_display_fields`.

in `basic_server.go`

on line `227`

If I change the line to

`ContinueGame: false,`

This shows up the in browser as (after I run the game)

`ContinueGame : false`

Which is what I want.

If keep the line as:

`ContinueGame: continue_game,`

The funny things happen if I try to click `Stop Turn`. It seems that `contintue_game` is false, according to logging, but is shows up as 

`ContinueGame: true,`

In the browser anyway, meaning that javascript parts get this `continue_game` as `true`.

I have no idea why!

**Comment by a-temlyakov** [comment]
It looks like in stopTurn() on line 72 in zombie_dice.html we never call the parseTurnData(data) function. That means whatever we return from the API call never gets parsed.

**Comment by Akavall** [comment]
Yeah, I fixed that. And that did it. Thank You.
